nice_urls: true

plugins:
    path: APP_PATH/../site/plugins
    config:
        markdown:
            twig: true
        simplecontact:
          twig: true
        simplesearch:
            twig: true
        textile:
            twig: true
    enable:
        - simplecontact
        - simplesearch

twig:
  debug: true
