language: en
locale: en_US.UTF-8

nice_urls: true

layouts:
    extension: 'twig'

plugins:
    path: APP_PATH/../site/plugins
    config:
        markdown:
            twig: true
        simplecontact:
          twig: true
        simplesearch:
            no_page: true
            twig: true
        textile:
            twig: true
    enable:
        - simplecontact
        - simplesearch

twig:
  debug: true
